In [2]:
# Load Models
import pandas as pd
import pickle
from tensorflow.keras.models import load_model

with open('final_pipeline.pkl','rb') as file_1:
  model_pipeline = pickle.load(file_1)

model_seq = load_model('model_seq.h5')
model_seq1 = load_model('model_seq1.h5')
model_func = load_model('model_func.h5')
model_func1 = load_model('model_func1.h5')

import warnings
warnings.filterwarnings('ignore')

In [3]:
#load data
df = pd.read_csv('D:\Hacktiv8\p2---ftds-019-rmt---m1-Novanska\churn.csv')

In [4]:
#mengambil inference dari sample 10 data dari df.
df_inf = df.sample(10)

In [5]:
#drop data yang tidak dibutuhkan
df_inf.drop(['churn_risk_score','user_id','internet_option','last_visit_time'],axis=1,inplace=True)

In [11]:
df_inf

age gender region_category  membership_category joining_date  \
22820   31      M            City    Silver Membership   2015-03-03   
4556    64      F         Village      Gold Membership   2017-08-25   
24901   52      M         Village        No Membership   2015-01-05   
18609   58      M             NaN  Platinum Membership   2015-04-29   
18735   32      F            Town  Platinum Membership   2015-02-24   
35183   43      M            City      Gold Membership   2015-01-03   
36875   36      F             NaN     Basic Membership   2016-07-18   
4044    47      F         Village      Gold Membership   2015-12-24   
6187    41      F            Town      Gold Membership   2017-10-03   
32205   16      F         Village  Platinum Membership   2017-04-09   

      joined_through_referral     preferred_offer_types medium_of_operation  \
22820                     Yes            Without Offers          Smartphone   
4556                      Yes            Without Offers                 NaN   
24901                     NaN     Gift Vouchers/Coupons          Smartphone   
18609                      No            Without Offers                 NaN   
18735                     Yes     Gift Vouchers/Coupons          Smartphone   
35183                     Yes  Credit/Debit Card Offers                Both   
36875                      No            Without Offers                 NaN   
4044                       No  Credit/Debit Card Offers             Desktop   
6187                      Yes            Without Offers          Smartphone   
32205                     Yes            Without Offers                Both   

       days_since_last_login  avg_time_spent  avg_transaction_value  \
22820                      9            0.00               21122.06   
4556                      11           30.95               36655.04   
24901                     16          202.86               32281.20   
18609                     13          324.56               36772.85   
18735                      6          156.92               10336.16   
35183                     11          255.60               33062.59   
36875                     22           33.25               48502.48   
4044                    -999           57.52               45957.68   
6187                      13          657.46               19373.70   
32205                      9          726.08               65554.05   

       avg_frequency_login_days  points_in_wallet used_special_discount  \
22820                       0.0        793.070000                    No   
4556                       28.0        221.588107                    No   
24901                      25.0        568.000000                   Yes   
18609                      16.0          0.000000                    No   
18735                       0.0        756.510000                   Yes   
35183                      22.0        634.850000                    No   
36875                       0.0        582.230000                   Yes   
4044                       27.0        243.062846                    No   
6187                       13.0        718.640000                   Yes   
32205                       3.0        825.960000                   Yes   

      offer_application_preference past_complaint          complaint_status  \
22820                          Yes             No            Not Applicable   
4556                           Yes             No            Not Applicable   
24901                           No             No            Not Applicable   
18609                          Yes            Yes  No Information Available   
18735                           No            Yes  No Information Available   
35183                          Yes             No            Not Applicable   
36875                           No             No            Not Applicable   
4044                           Yes             No            Not Applicable   
6187                           Yes  

In [6]:
# Transform Inference-Set

df_inf_transform = model_pipeline.transform(df_inf)
df_inf_transform

array([[-4.01360432e-01, -4.45940452e-01, -1.02073616e+00,
        -4.14637521e-01, -1.55326937e+00,  6.48205963e-01,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 1.66

In [7]:
#predict dengan model_sequential
import numpy as np
y_pred_inf = model_seq.predict(df_inf_transform)
y_pred_inf = np.where(y_pred_inf >= 0.5,1,0)
y_pred_inf

1/1 [==============================] - 1s 657ms/step


array([[0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0]])

In [8]:
#predict dengan model_sequential improvement
y_pred_inf = model_seq1.predict(df_inf_transform)
y_pred_inf = np.where(y_pred_inf >= 0.5,1,0)
y_pred_inf

1/1 [==============================] - 0s 179ms/step


array([[0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0]])

In [9]:
#predict dengan model_functional
y_pred_inf = model_func.predict(df_inf_transform)
y_pred_inf = np.where(y_pred_inf >= 0.5,1,0)
y_pred_inf

1/1 [==============================] - 0s 157ms/step


array([[0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0]])

In [10]:
#predict dengan model functional improvement
y_pred_inf = model_func1.predict(df_inf_transform)
y_pred_inf = np.where(y_pred_inf >= 0.5,1,0)
y_pred_inf

1/1 [==============================] - 0s 94ms/step


array([[0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0]])

Insight :

dari data sequential,sequential improvement, terdapat 5 customers yang akan churn, namun menurut functional terdapat 3 customer yang akan churn dan pada functional improvement akan ada 6 customers yang akan churn.